<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>任务分配系统</title>
        <meta name="keywords" content="任务分配系统" />
        <meta name="description" content="任务分配系统" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/icon" />
    </head>
    <body>
        *******************************<br/>
        <?php echo $this->content; ?><br/>
        *******************************<br/>
    </body>
</html>